// 개발용: 템플릿을 가짜 데이터로 렌더해 문법 오류를 찾는다. 가짜 데이터에 같은 키가 겹쳐도 괜찮다
/* eslint-disable no-dupe-keys */
import Handlebars from "handlebars";
import fs from "node:fs";
const root = process.argv[2];
const H = Handlebars;
for (const h of ["localize","selectOptions","checked","editor"]) H.registerHelper(h, () => "");
H.registerHelper("nssqLabel", (p,k)=>`${p}.${k}`); H.registerHelper("nssqEq",(a,b)=>a===b); H.registerHelper("nssqGt",(a,b)=>a>b); H.registerHelper("nssqSigned",(n)=>String(n));
for (const p of ["actor/parts/inventory","actor/parts/skills","actor/parts/refine-badges"]) H.registerPartial(`systems/nssq/templates/${p}.hbs`, fs.readFileSync(`${root}/templates/${p}.hbs`,"utf8"));
const sys = {abilities:{str:1},bonus:{str:0},sub:{},resist:{},stats:{},hp:{},tp:{},fp:{}};
for (const t of ["chat/attack-card","apps/gm-screen","apps/shop","chat/ability-roll","chat/check-card","actor/character-sheet","actor/enemy-sheet","actor/token-sheet","item/item-sheet","apps/skill-tree"]) {
  try { H.compile(fs.readFileSync(`${root}/templates/${t}.hbs`,"utf8"),{strict:false})({system:sys,actor:{},item:{},abilityKeys:["str"],abilityRows:[{key:"str",base:1,class:2,growth:0,equip:0,temp:0,total:3,bonus:0}],classes:{main:{}},inventory:{skillGroups:[{title:"t",cls:"main",skills:[{id:"s",name:"n",timing:"상시",max:3}]}],slots:[{slot:"weapon",label:"x",item:{id:"a",refinable:true}}],groups:[{label:"x",items:[{id:"b",stackable:true,equippable:true,canSub:true}]}],classes:[],skills:[{system:{}}]},resistRows:[{key:"slash",changed:true}],stats:[{label:"a",value:1}],refinements:[{key:"k",name:"n"}],party:[{id:"a",hp:{},tp:{},npc:true}],npcCandidates:[{id:"n"}],presets:[{id:"p",thumb:"x",bg:false}],battle:{name:"b"},canAttack:true,isGM:true,editable:true,hpPct:50,tpPct:20,drops:[{range:"4~7",item:"R1 x"}],attackElementText:"x",sheet:{growth:{left:1},canRollAbilities:true,abilityCards:[{key:"str",short:"STR",total:1,b:0,tooltip:"t"}],resist:[{key:"fire",label:"x",base:3,total:4,changed:true}],subStats:[{key:"a",label:"b",value:1}],equip:[{slot:"weapon",item:null},{slot:"armor",item:{id:"i",name:"n",refine:{badges:[],empty:[0]}}}],weaponLine:"w",creation:{locked:false,total:9,rollCount:1,totals:[1,2],entries:[{when:"a",user:"b",text:"c"}],assign:"x"}},showNpcToggle:true,elementText:"x",targets:[{hit:true,hitDice:[1,6],dmg:[{v:4,over:true}],crit:true,crit4:[{v:2}]}],shopGroups:[{type:"tool",items:[{uuid:"u",name:"n",selling:false,custom:true}]}],targets:[{value:7}],abilityUses:[{}],levels:[{}],sessionExp:[{}],tabs:[{type:"weapon",rows:[{id:"x",ranked:true}]}],sellRows:[{id:"s",multi:true,refine:{badges:[{icon:"a",text:"b"}],empty:[0]}}],refineRows:[{id:"r",refine:null}],tabs:[{key:"main",label:"x",active:true}],nodes:[{id:"a",name:"n",x:1,y:2,current:1,maxText:"3/2",unique:true,state:"open",canRaise:true}],edges:[{d:"M",lx:1,ly:2,sl:2,met:true,any:true}],hasTree:true,independent:[{id:"b",name:"m"}],budget:{left:-1},width:10,height:10,mainClassChoices:{},subClassChoices:{},subKeys:["x"],resistKeys:["slash"],items:[{type:"skill"}],fields:[{type:"NumberField"}],dice:[{v:1,i:0,used:true,one:true}],many:true,modifier:2,hasTarget:true,success:true}); console.log("ok", t); }
  catch(e){ console.log("FAIL", t, e.message); }
}
